version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: financesbox
      POSTGRES_PASSWORD: financesbox
      POSTGRES_DB: core
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - financesbox_net

networks:
  financesbox_net:

volumes:
  postgres_data:
