micronaut:
  application:
    name: core-api
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    enabled: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
  command:
    timeoutInMillis: ${MICRONAUT_COMMAND_TIMEOUT_IN_MILLIS:15000}
  query:
    timeoutInMillis: ${MICRONAUT_QUERY_TIMEOUT_IN_MILLIS:15000}

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:core}
    username: ${POSTGRES_USERNAME:financesbox}
    password: ${POSTGRES_PASSWORD:financesbox}

liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

jackson:
  serializationInclusion: ALWAYS

command.implementation: ${COMMAND_IMPLEMENTATION:MICRONAUT}
query.implementation: ${QUERY_IMPLEMENTATION:MICRONAUT}
event.implementation: ${EVENT_IMPLEMENTATION:MICRONAUT}